### ISSUE TITLE
Can't install V2

### ISSUE THREAD

**Issue by XaviMPCD02** [astrojolo/astrolink4pi#11]
I tried to install V2 (https://github.com/astrojolo/astrolink4pi/tree/3.0.0) in Raspberry Pi4 4Gb with the updated STELLARMATE
My astrolink is one of the first units, with jack sensor, no RTC.
Followed this steps:

sudo apt update
sudo apt install git
sudo apt-get install build-essential
sudo apt-get install cmake
sudo apt-get install libindi-dev
sudo apt-get install gpiod libgpiod-dev libgpiod-doc
sudo systemctl enable pigpiod

Then

git clone https://github.com/astrojolo/astrolink4pi
cd astrolink4pi
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make

But I get this errors and I don't have enough skills to solve it:

stellarmate@stellarmate:~/astrolink4pi/build $ make
[ 50%] Building CXX object CMakeFiles/indi_astrolink4pi.dir/astrolink4pi.o
/home/stellarmate/astrolink4pi/astrolink4pi.cpp: In member function 'virtual void AstroLink4Pi::TimerHit()':
/home/stellarmate/astrolink4pi/astrolink4pi.cpp:1007:38: error: 'class INDI::PropertyNumber' has no member named 's'
 1007 |                         ParametersNP.s = IPS_OK;
      |                                      ^
/home/stellarmate/astrolink4pi/astrolink4pi.cpp:1013:38: error: 'class INDI::PropertyNumber' has no member named 's'
 1013 |                         ParametersNP.s = IPS_ALERT;
      |                                      ^
/home/stellarmate/astrolink4pi/astrolink4pi.cpp:1016:30: error: 'INDI::PropertyView<T>* INDI::PropertyBasic<T>::operator&() [with T = _INumber]' is protected within this context
 1016 |                 IDSetNumber(&ParametersNP, nullptr);
      |                              ^~~~~~~~~~~~
In file included from /usr/include/libindi/indipropertytext.h:21,
                 from /usr/include/libindi/basedevice.h:29,
                 from /usr/include/libindi/parentdevice.h:3,
                 from /usr/include/libindi/defaultdevice.h:21,
                 from /home/stellarmate/astrolink4pi/astrolink4pi.h:39,
                 from /home/stellarmate/astrolink4pi/astrolink4pi.cpp:19:
/usr/include/libindi/indipropertybasic.h:115:27: note: declared protected here
  115 |         PropertyView<T> * operator &();
      |                           ^~~~~~~~
make[2]: *** [CMakeFiles/indi_astrolink4pi.dir/build.make:76: CMakeFiles/indi_astrolink4pi.dir/astrolink4pi.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/indi_astrolink4pi.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by astrojolo** [comment]
Older AL 4 Pi versions support was moved to https://github.com/astrojolo/astrolink4pi/tree/3.0 branch now. 
Compilation was fixed, and README was updated.

Clear skies,
Lucas
