### ISSUE TITLE
Stellarmate issues/Upgrades

### ISSUE THREAD

**Issue by XaviMPCD02** [astrojolo/astrolink4pi#12]
Hi again Lucas

It seems Astroberry is no longer updated so I have switched to Stellarmate...

In the options tab I have a label "Capture Device > Telescope". 
When I set the mount driver (EqMod) in that line, I was able to read the Step size and Critical Focus Zone in the first tab ("Main Control").
But the Eqmod Driver has no longer any information about the optical train, so I tried another driver that has that information, but the Astrolink4Pi driver can't read it.
Maybe it is better to fill that information manually?

Also, I'd like to ask about the "System" tab: there is a line labeled "Load (1/5/15 min.) but I can't figure out how to read it because only the center digit is changing (0/17/0, 0/25/0, etc.).

Thank you!
Xavier

**Comment by astrojolo** [comment]
Hi Xavier,

Thank you for that report - I also noticed it and have it on my list. It should be fixed within 1-2 weeks. 

As for the Load field - these values are read from the system variable that reports the average CPU load over 1, 5, and 15 minutes. It used to work correctly, but I will take a closer look - maybe something changed in RPi5.

Lucas

**Comment by astrojolo** [comment]
Hi Xavier, 

Can you check if your driver is up to date? There should be two fields scope aperture and focal length to fill manually (like in the manual, page 13) in the latest driver version. Can you confirm?
As for the CPU load - I still need to verify that.

Lucas

**Comment by XaviMPCD02** [comment]
I don't see any difference. There is the same field: "Capture Device > Telescope".
Driver is updated. 
I must say I'm using V1.2 (Interface 32904) for Astrolink4pi version 2 or earlier.

Xavier

**Comment by astrojolo** [comment]
Ups, I did not realize that :( 
I will take a look into my older AL 4 Pi at the end of this week.

Lucas

**Comment by XaviMPCD02** [comment]
Hi Lucas,

With some trouble I managed to install it and it works perfectly. I don't handle Linux quite well, excuse me!

Since I wasn't able to update it, I removed and reinstalled it. If I follow the instructions in the 3.0.1 branch I get the following error:
`stellarmate@stellarmate:~ $ git clone https://github.com/astrojolo/astrolink4pi
cd astrolink4pi
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
Clonando en 'astrolink4pi'...
remote: Enumerating objects: 2286, done.
remote: Counting objects: 100% (1177/1177), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 2286 (delta 1067), reused 1054 (delta 1025), pack-reused 1109 (from 1)
Recibiendo objetos: 100% (2286/2286), 19.08 MiB | 19.93 MiB/s, listo.
Resolviendo deltas: 100% (1532/1532), listo.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found INDI: /usr/lib/aarch64-linux-gnu/libindidriver.so;/usr/lib/aarch64-linux-gnu/libindiAlignmentDriver.so (found version "2.0.9") 
-- Performing Test COMPATIBLE_FORTIFY_SOURCE
-- Performing Test COMPATIBLE_FORTIFY_SOURCE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stellarmate/astrolink4pi/build
[ 50%] Building CXX object CMakeFiles/indi_astrolink4pi.dir/astrolink4pi.o
In file included from /home/stellarmate/astrolink4pi/astrolink4pi.cpp:19:
/home/stellarmate/astrolink4pi/astrolink4pi.h:38:10: fatal error: lgpio.h: No existe el fichero o el directorio
   38 | #include <lgpio.h>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/indi_astrolink4pi.dir/build.make:76: CMakeFiles/indi_astrolink4pi.dir/astrolink4pi.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/indi_astrolink4pi.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

What I did was modify the instructions given for "Devices revision 2 and earlier" in the main branch like:
`git clone https://github.com/astrojolo/astrolink4pi
cd astrolink4pi
mkdir build && cd build
**git checkout 3.0.1**
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
sudo make install`

And that was enough to run fine!
Thanks Lucas

Xavier

**Comment by astrojolo** [comment]
Thanks a lot for testing and sharing the outcome! I will update the readme and close this issue.
