### ISSUE TITLE
Wrong step value when reverse motion is on

### ISSUE THREAD

**Issue by XaviMPCD02** [astrojolo/astrolink4pi#3]
When reverse motion is on and it moves outwards, a simple 100 step movement sets absolute position to a disproportionate value (4294966553), so it keeps moving until the focuser hits the end
![Captura desde 2022-09-20 00-08-152](https://user-images.githubusercontent.com/113947336/191129730-430f5bc2-ff4a-4cd3-aad0-ce0bd6fe3c7f.png)

**Comment by astrojolo** [comment]
Thank you for that - it was fixed.
